[package]
name = "icy_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["advanced", "image", "tokio", "lazy", "debug"] }
smol_str = "0.2.2"
tokio = { version = "1.39.2", features = ["time"] }
ul-next = { version = "0.2.0", optional = true }

[features]
default = ["webkit"]
webkit = ["ultralight"]
ultralight = ["ul-next"]
