[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["advanced", "image", "tokio", "lazy"] }
ul-next = { version = "0.2.0", optional = true }

[features]
default = ["webkit"]
webkit = ["ultralight"]
ultralight = ["ul-next"]
