[package]
name = "icy_browser"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"
description = "iced browser widgets"
repository = "https://github.com/LegitCamper/icy_browser"

[profile.dev]
incremental = true
opt-level = "s"
lto = "thin"

[features]
default = ["ultralight", "ultralight-resources"]
ultralight = ["iced_webview/ultralight"]
ultralight-resources = ["iced_webview/ultralight-resources"]

[dependencies.iced_webview]
git = "https://github.com/LegitCamper/iced_webview"
default-features = false

[dependencies]
iced = { version = "0.13", features = ["advanced", "image", "tokio", "lazy"] }
iced_aw = { version = "0.10", features = ["tab_bar", "selection_list"] }
iced_fonts = { version = "0.1.1", features = ["bootstrap"] }
iced_on_focus_widget = "0.1.1"
iced_event_wrapper = { git = "https://github.com/LegitCamper/iced_event_wrapper" }
url = "2.5.2"
